spring:
  application:
    name: nev
  profiles:
    active: development
  #      active: production
  jackson:
    date-format: "yyyy/MM/dd"
  thymeleaf:
    prefix: classpath:/templates/
#  servlet:
    multipart:
      enabled: true
      # Threshold after which files will be written to disk.
      file-size-threshold: 0
      max-file-size: 10MB
      max-request-size: 20MB
  #      location:
  #      resolve-lazily: true
  transaction:
    # Default transaction timeout in seconds.
    default-timeout: 3600
    # Perform the rollback on commit failures.
    rollback-on-commit-failure: true
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080
  servlet:
#    context-path: /nev
    session:
      cookie:
        http-only: true

---
# Configuration for development env
spring:
  profiles: development
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true
  resources:
    # Static resources reloading during development
    static-locations: classpath:/resources/static
    cache:
      period: 0

application:
  path:
    upload: /Users/khoibv/tmp/stp/upload
    download: /Users/khoibv/tmp/stp/download
    avatar: /Users/khoibv/tmp/stp/avatar
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization,Link,X-Total-Count"
    allow-credentials: true
    max-age: 1800
  github:
    enable-fork: true

---
# Configuration for production env
spring:
  profiles: production
  thymeleaf:
    cache: true

application:
  path:
    upload: /var/stp/files/upload
    download: /var/stp/files/download
    avatar: /var/stp/files/avatar
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization,Link,X-Total-Count"
    allow-credentials: true
    max-age: 1800
  github:
    enable-fork: false

